# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: [https://core.newebpay.com/EPG/boutiquebitmap/aQJIdj, https://github.com/scott0107000/BoutiqueBitmap9x9/blob/c49f6d2da68525697fe4338a7caeb1d47895d6ed/%E5%AE%98%E6%96%B9%E5%94%AF%E4%B8%80%E8%B4%8A%E5%8A%A9%E7%AE%A1%E9%81%93.png]
